version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:uPxBHn%5DAg9H~N4%27K@20.84.99.214:443/jf100124
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    
  # Opcional: Base de datos PostgreSQL local para desarrollo
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: estudiantes_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: